import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :base_acl_ex, BaseAclExWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Rate limiting configuration for production
# Strict limits for production environment
config :base_acl_ex,
  rate_limiting_enabled: true,
  rate_limiting_log_enabled: true,
  rate_limiter_cache: [
    # Large cache for production
    limit: 500_000,
    # 10 minutes
    cleanup_interval: 600_000
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
